config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms do
  	resource :chatroom_users
  	resources :messages
  	collection do
  		get 'all_users'
  		post 'get_users_chatroom'
  	end
  end
  root "chatrooms#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users
	has_many :messages
	after_create :map_users_for_chat

	def map_users_for_chat
		if self.chatroom_type==0
			users=self.name.split("_")
			self.chatroom_users.create(user_id: users[0])
			self.chatroom_users.create(user_id: users[1])
		end
	end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	include DeviseWhitelist
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
	before_action :set_chatroom

	def create
		@chatroom_user=@chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
		redirect_to @chatroom
	end

	def destroy
		@chatroom_user=@chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
		redirect_to chatrooms_path
	end

	private
	def set_chatroom
		@chatroom=Chatroom.find(params[:chatroom_id])
	end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.where("chatroom_type=1")
    respond_to do |format|
      format.js{render partial: 'chatroom_router.js.erb',locals:{from: :index}}
      format.html{render 'index.html.erb'}
    end
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages=@chatroom.messages.order(created_at: :desc).limit(100).reverse
    respond_to do |format|
      format.js{render partial: 'chatroom_router.js.erb',locals:{from: :show}}
      format.html{render 'show.html.erb'}
    end
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  def all_users
    @users = User.all-[current_user]
    respond_to do |format|
      format.js{render partial: 'chatroom_router.js.erb',locals:{from: :all_users}}
    end
  end
  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.created_by=current_user.id
    respond_to do |format|
      if @chatroom.save
        @chatroom_user=@chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_users_chatroom
    params[:name]=(params[:user_id].to_i<current_user.id) ? "#{params[:user_id]}_#{current_user.id}" : "#{current_user.id}_#{params[:user_id]}"
    params[:chatroom_type]=0
    @chatroom=Chatroom.where(name: params[:name],chatroom_type: params[:chatroom_type]).first_or_create
    redirect_to @chatroom
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name, :chatroom_type)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern
	included do 
		before_action :configure_params, if: :devise_controller?
	end
	
	def configure_params
		added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
		devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_chatroom

	def create
		message=@chatroom.messages.new(message_params)
		message.user=current_user
		message.save
		MessageRelayJob.perform_later(message)
	end

	def destroy
		
	end

	private
	def set_chatroom
		@chatroom=Chatroom.find(params[:chatroom_id])
	end

	def message_params
		params.require(:message).permit(:body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_chatroom_name(chatroom)
		if chatroom.chatroom_type==1
			return chatroom.name
		else
			return User.find_by_id((chatroom.name.split("_")-[current_user.id.to_s]).last.to_i).username
		end
	end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_all_users.html.erb
<center>
<table style="width:90%">
  <thead>
    <tr>
      <th style="width:85%"></th>
      <th style="width:15%"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.username}", get_users_chatroom_chatrooms_path(user_id: user.id), method: :post ,class: 'chatrooms_list_links_leftpanel'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

app/views/chatrooms/_chatroom_router.js.erb
<%case from%>
<%when :index%>
	$("#chatrooms").html("<%=j render partial:'index'%>");
<%when :all_users%>
	$("#chatrooms").html("<%=j render partial:'all_users'%>");
<%when :show%>
	$("#main-timeline").html("<%=j render partial:'show'%>");
<%end%>

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.number_field :chatroom_type, value: 1, style: 'display:none;' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/_index.html.erb
<center>
  <table  style="width:90%">
    <thead>
      <tr>
      <th style="width:85%"></th>
        <th colspan="3" style="width:15%"></th>
      </tr>
    </thead>

    <tbody>
      <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= link_to "#{chatroom.name}", chatroom_chatroom_users_path(chatroom), method: :post ,class: 'chatrooms_list_links_leftpanel'%></td>
        <%if chatroom.created_by==current_user.id%>
        <td><%= link_to "<img src='#{asset_path('edit.png')}' height='18' width='18' title='Edit' alt='Edit'>".html_safe, edit_chatroom_path(chatroom) %></td>
        <td>&nbsp;</td>
        <td><%= link_to "<img src='#{asset_path('delete.png')}' height='18' width='18' title='Delete' alt='Delete'>".html_safe, chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <%end%>
      </tr>
      <% end %>
    </tbody>
  </table>
</center>

app/views/chatrooms/_show.html.erb
	<p id="notice"><%= notice %></p>

	<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<!-- <div class="img_cont">
									<img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img">
									<span class="online_icon"></span>
								</div> -->
								<div class="user_info">
									<span><%= get_chatroom_name(@chatroom) %></span>
									<p><%=@chatroom.messages.count%> Messages</p>
								</div>
								<div class="video_cam">
									<span><i class="fas fa-video"></i></span>
									<span><i class="fas fa-phone"></i></span>
								</div>
							</div>
							<span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
							<div class="action_menu">
								<ul>
									<li><i class="fas fa-user-circle"></i> View profile</li>
									<li><i class="fas fa-users"></i> Add to close friends</li>
									<li><i class="fas fa-plus"></i> Add to group</li>
									<li><i class="fas fa-ban"></i> Block</li>
								</ul>
							</div>
						</div>

							

	<div data-behavior='messages' data-chatroom-id="<%=@chatroom.id%>" id="chatroom_panel_<%=@chatroom.id%>" class="card-body msg_card_body">
		<% @messages.each do |message| %>
		<div class="d-flex justify-content-start mb-4 justify-content-<%=message.user.id%>">
		<!-- <div class="img_cont_msg">
		<img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img_msg">
			</div> -->
			<div class="msg_cotainer msg_cotainer_<%=message.user.id%>">
				<strong><%= message.user.username%>:</strong><%=message.body%>
				<span class="msg_time msg_time_<%=message.user.id%>"><%=message.created_at.strftime("%d-%m-%y %H:%M")%></span>
			</div>
		</div>
		<%end%>
	</div>

	<%=form_for [@chatroom, Message.new], authenticity_token: true do |f|%>
		<div class="card-footer">
			<div class="input-group">
				<div class="input-group-append">
					<span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
				</div>
					<%= f.text_area :body, rows:1, class: "form-control type_msg",placeholder: "Type your message...", autofocus: true%>
				<div class="input-group-append">
					<span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
				</div>
			</div>
		</div>
	<%end%>
	
	<script type="text/javascript">
		$('#chatroom_panel_<%=@chatroom.id%>').css('height',($(window).height()-132))
		setTimeout(function() {
			$('#chatroom_panel_<%=@chatroom.id%>').animate({ scrollTop: $('#chatroom_panel_<%=@chatroom.id%>').prop("scrollHeight")}, 1000);
		}, 500);
	</script>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<%=link_to "Logout",destroy_user_session_path,method: :delete,class:"btn btn-outline-danger" if current_user%>
<br>
<table id="chatroom_listing_headers">
<tr>
<td style="width: 49%" align="center" class="header_active"><%= link_to '<span>Chatrooms</span>'.html_safe, chatrooms_path, method: :get, remote: true,class: "chatrooms_list_links",onclick: "$('#chatroom_listing_headers').find('td').removeClass('header_active');$(this).parent('td').addClass('header_active');"%></td><td style="width: 2%" align="center"><b>|</b></td><td style="width: 49%" align="center"><%= link_to '<span>Users</span>'.html_safe, all_users_chatrooms_path, method: :get, remote: true,class: "chatrooms_list_links",onclick: "$('#chatroom_listing_headers').find('td').removeClass('header_active');$(this).parent('td').addClass('header_active');"%></td>
</tr>
</table>
<br>
<div id="chatrooms">
<center>
<table style="width:90%">
  <thead>
    <tr>
      <th style="width:85%"></th>
      <th colspan="3" style="width:15%"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= link_to "#{chatroom.name}", chatroom_chatroom_users_path(chatroom), method: :post ,class: 'chatrooms_list_links_leftpanel'%></td>
        <%if chatroom.created_by==current_user.id%>
          <td><%= link_to "<img src='#{asset_path('edit.png')}' height='18' width='18' title='Edit' alt='Edit'>".html_safe, edit_chatroom_path(chatroom) %></td>
          <td>&nbsp;</td>
          <td><%= link_to "<img src='#{asset_path('delete.png')}' height='18' width='18' title='Delete' alt='Delete'>".html_safe, chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
</div>
<br>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
	<p id="notice"><%= notice %></p>

	<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<!-- <div class="img_cont">
									<img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img">
									<span class="online_icon"></span>
								</div> -->
								<div class="user_info">
									<span><%= get_chatroom_name(@chatroom) %></span>
									<p><%=@chatroom.messages.count%> Messages</p>
								</div>
								<div class="video_cam">
									<span><i class="fas fa-video"></i></span>
									<span><i class="fas fa-phone"></i></span>
								</div>
							</div>
							<span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
							<div class="action_menu">
								<ul>
									<li><i class="fas fa-user-circle"></i> View profile</li>
									<li><i class="fas fa-users"></i> Add to close friends</li>
									<li><i class="fas fa-plus"></i> Add to group</li>
									<li><i class="fas fa-ban"></i> Block</li>
								</ul>
							</div>
						</div>

							

	<div data-behavior='messages' data-chatroom-id="<%=@chatroom.id%>" id="chatroom_panel_<%=@chatroom.id%>" class="card-body msg_card_body">
		<% @messages.each do |message| %>
		<div class="d-flex justify-content-start mb-4 justify-content-<%=message.user.id%>">
		<!-- <div class="img_cont_msg">
		<img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img_msg">
			</div> -->
			<div class="msg_cotainer msg_cotainer_<%=message.user.id%>">
				<strong><%= message.user.username%>:</strong><%=message.body%>
				<span class="msg_time msg_time_<%=message.user.id%>"><%=message.created_at.strftime("%d-%m-%y %H:%M")%></span>
			</div>
		</div>
		<%end%>
	</div>

	<%=form_for [@chatroom, Message.new], authenticity_token: true do |f|%>
		<div class="card-footer">
			<div class="input-group">
				<div class="input-group-append">
					<span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
				</div>
					<%= f.text_area :body, rows:1, class: "form-control type_msg",placeholder: "Type your message...", autofocus: true%>
				<div class="input-group-append" onclick='$(this).submit();'>
					<span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
				</div>
			</div>
		</div>
	<%end%>
	
	<script type="text/javascript">
		$('#chatroom_panel_<%=@chatroom.id%>').css('height',($(window).height()-132))
		setTimeout(function() {
			$('#chatroom_panel_<%=@chatroom.id%>').animate({ scrollTop: $('#chatroom_panel_<%=@chatroom.id%>').prop("scrollHeight")}, 1000);
		}, 500);
		$(document).ready(function(){
			$('#action_menu_btn').click(function(){
				$('.action_menu').toggle();
			});
		});
	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatbox</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
</head>

<body>
  <div class="container-fluid h-100">
    <div class="row justify-content-center h-100">
      
        <%if current_user%>
        <div class="col-md-4 col-xl-3 chat">
        <style type="text/css">
          .msg_cotainer_<%=current_user.id%>{
            margin-right: 10px !important;
            background-color: #78e08f !important;
          }
          .msg_time_<%=current_user.id%>{
            right:0 !important;
          }
          .justify-content-<%=current_user.id%>{
            justify-content: flex-end!important;
          }
        </style>
        <div class="card mb-sm-3 mb-md-0 contacts_card">
        <div>
          <%= link_to '<span>Chatrooms</span>'.html_safe, chatrooms_path, method: :get,class: "chatrooms_link"%>
          <%= link_to 'New Chatroom', new_chatroom_path ,class:"btn btn-outline-warning new_chatroom_link"%>
        </div>
          <div class="card-header">
            <div class="input-group">
              <input type="text" placeholder="Search..." name="" class="form-control search">
              <div class="input-group-prepend">
                <span class="input-group-text search_btn"><i class="fas fa-search"></i></span>
              </div>
            </div>
          </div>
          <div class="card-body contacts_body">
            <ui class="contacts">
              <%current_user.chatrooms.each do |chatroom|%>
              <li class='all_chatrooms_list <%='active' if !@chatroom.nil? and @chatroom.id==chatroom.id%>'>
                <div class="d-flex bd-highlight">
                <!-- <div class="img_cont">
                  <img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img">
                  <span class="online_icon"></span>
                </div> -->
                <div class="user_info" style="width:100%;">
                  <span style="float:left;"><%=link_to "#{get_chatroom_name(chatroom)}", chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id},class: 'chatrooms_list_links_leftpanel'%></span> &nbsp; <span style="float:right;margin-right: 20px;"><%= link_to "<img src='#{asset_path('cross_3d.png')}' height='15' width='15' title='Leave' alt='Leave'>".html_safe, chatroom_chatroom_users_path(chatroom), method: :delete if chatroom.chatroom_type==1%></span>
                  <!-- <p>Maryam is online</p> -->
                </div>
              </div>
            </li>
            <%end%>
          </ui>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-xl-6 chat">
      <div class="card" id="main-timeline">
        <%=yield%>
      </div>
    </div>
    <%else%>
    <div class="col-md-12 col-xl-6 chat">
      <div class="card" id="main-timeline">
        <%=yield%>
      </div>
    </div>
    <%end%>
  </div>
</div>
</body>
</html>

app/views/messages/_message.html.erb
		<div class="d-flex justify-content-start mb-4 justify-content-<%=message.user.id%>">
		<!-- <div class="img_cont_msg">
		<img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img_msg">
			</div> -->
			<div class="msg_cotainer msg_cotainer_<%=message.user.id%>">
				<strong><%= message.user.username%>:</strong><%=message.body%>
				<span class="msg_time msg_time_<%=message.user.id%>"><%=message.created_at.strftime("%d-%m-%y %H:%M")%></span>
			</div>
		</div>
<script>
	$('#chatroom_panel_<%=message.chatroom.id%>').animate({ scrollTop: $('#chatroom_panel_<%=message.chatroom.id%>').prop("scrollHeight")}, 500);
</script>

app/views/messages/create.js.erb
$("#new_message")[0].reset()